version: "3"
services:
  postgresbd:
    image: postgres:latest
    container_name: docker_desafio_conductor_bd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=desafio_conductor
    restart: always
  postgresbd_1:
    image: postgres:latest
    container_name: docker_desafio_conductor_bd_1
    volumes:
      - postgres-data_1:/var1/lib/postgresql/data
    expose:
    - 5433
    ports:
      - 5433:5433
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=desafio_conductor
    restart: always
  postgresbd_2:
    image: postgres:latest
    container_name: docker_desafio_conductor_bd_2
    volumes:
      - postgres-data_2:/var2/lib/postgresql/data
    expose:
    - 5434
    ports:
      - 5434:5434
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=desafio_conductor
    restart: always
# APP*****************************************
  springbootapp:
    build: 
        context: "."
        dockerfile: Dockerfile
    container_name: app_desafio_conductor
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgresbd
      - postgresbd_1
      - postgresbd_2
    links:
      - postgresbd
      - postgresbd_1
      - postgresbd_2
volumes:
  postgres-data:
  postgres-data_1:
  postgres-data_2:
